import mongoose,{Types} from 'mongoose';
import PDFDocument from 'pdfkit';
import { AppError } from '../../shared/errors/app-error';
import { Purchase } from '../models/purchase.model';
import { Supplier } from '../../suppliers/models/supplier.model';
import { Product } from '../../products/models/product.model';
import { InventoryMovement } from '../../products/models/inventory-movement.model';

export class PurchaseService {
 async list(tenantId:string){const data=await Purchase.find({tenantId}).sort({purchaseDate:-1}).limit(100).lean().exec();return {data,pagination:{total:data.length,page:1,limit:100,hasMore:false}};}
 async create(tenantId:string,userId:string,input:any){if(!mongoose.isValidObjectId(input.supplierId)||!Array.isArray(input.items)||!input.items.length)throw new AppError('VALIDATION_ERROR','Proveedor y partidas son obligatorios',400);const supplier=await Supplier.findOne({_id:input.supplierId,tenantId,status:'active'}).exec();if(!supplier)throw new AppError('RESOURCE_NOT_FOUND','Proveedor no encontrado',404);const session=await mongoose.startSession();let result:any;try{await session.withTransaction(async()=>{const items:any[]=[];for(const line of input.items){const product=await Product.findOne({_id:line.productId,tenantId,status:'active'}).session(session).exec();const quantity=Number(line.quantity),unitCost=Number(line.unitCost);if(!product||!Number.isFinite(quantity)||quantity<=0||!Number.isFinite(unitCost)||unitCost<0)throw new AppError('VALIDATION_ERROR','Partida de compra inválida',400);const before=product.stock;product.stock+=quantity;product.costPrice=unitCost;await product.save({session});await InventoryMovement.create([{tenantId,productId:product._id,userId,type:'entry',quantity,stockBefore:before,stockAfter:product.stock,notes:'Entrada por compra'}],{session});items.push({productId:product._id,sku:product.sku,productName:product.name,quantity,unitCost,subtotal:Math.round(quantity*unitCost*100)/100});}const total=items.reduce((s,i)=>s+i.subtotal,0);const folio='C-'+Date.now()+'-'+new Types.ObjectId().toString().slice(-6).toUpperCase();[result]=await Purchase.create([{tenantId,folio,supplierId:supplier._id,supplierName:supplier.name,userId,items,total,notes:String(input.notes??''),isDemo:Boolean(input.isDemo)}],{session});});return result;}finally{await session.endSession();}}
 async pdf(tenantId:string,id:string){if(!mongoose.isValidObjectId(id))throw new AppError('VALIDATION_ERROR','Compra no válida',400);const purchase=await Purchase.findOne({_id:id,tenantId}).lean().exec();if(!purchase)throw new AppError('RESOURCE_NOT_FOUND','Compra no encontrada',404);return purchasePdf([purchase],`Reporte de compra ${purchase.folio}`);}
 async packagePdf(tenantId:string,ids:string[]){const valid=[...new Set(ids)].filter(id=>mongoose.isValidObjectId(id));if(!valid.length||valid.length>50)throw new AppError('VALIDATION_ERROR','Selecciona entre 1 y 50 compras',400);const purchases=await Purchase.find({_id:{$in:valid},tenantId}).sort({purchaseDate:1}).lean().exec();if(!purchases.length)throw new AppError('RESOURCE_NOT_FOUND','No se encontraron compras',404);return purchasePdf(purchases,`Paquete de compras (${purchases.length})`);}
}

function purchasePdf(purchases:any[],title:string):Promise<Buffer>{return new Promise((resolve,reject)=>{const doc=new PDFDocument({size:'A4',margin:40});const chunks:Buffer[]=[];doc.on('data',(c:Buffer)=>chunks.push(c));doc.on('error',reject);doc.on('end',()=>resolve(Buffer.concat(chunks)));try{doc.fontSize(18).fillColor('#022656').text('Apta Digital',{align:'center'});doc.moveDown(.2).fontSize(14).fillColor('#111827').text(title,{align:'center'});doc.moveDown(.3).fontSize(8).fillColor('#6b7280').text('Generado: '+new Date().toLocaleString('es-MX'),{align:'center'});doc.moveDown();let grand=0;for(const p of purchases){if(doc.y>690)doc.addPage();doc.fontSize(12).fillColor('#022656').text(String(p.folio));doc.fontSize(9).fillColor('#111827').text('Proveedor: '+p.supplierName+'   Fecha: '+new Date(p.purchaseDate).toLocaleDateString('es-MX'));doc.moveDown(.4);for(const item of p.items??[]){if(doc.y>730)doc.addPage();doc.fontSize(8).text(`${item.sku}  ${item.productName} | ${item.quantity} x ${money(item.unitCost)} = ${money(item.subtotal)}`);}doc.fontSize(10).text('Total compra: '+money(p.total),{align:'right'});grand+=Number(p.total)||0;doc.moveDown();doc.moveTo(40,doc.y).lineTo(555,doc.y).strokeColor('#d1d5db').stroke();doc.moveDown();}doc.fontSize(13).fillColor('#022656').text('TOTAL DEL REPORTE: '+money(grand),{align:'right'});doc.end();}catch(e){reject(e);}});}
function money(v:number){return new Intl.NumberFormat('es-MX',{style:'currency',currency:'MXN'}).format(Number(v)||0);}
