import React, { useEffect, useMemo, useState } from 'react';
import { apiDownload, apiDownloadPost, apiErrorMessage, apiRequest, type Session } from '../api/client';

type Row=Record<string,unknown>;
type Kind='customers'|'suppliers'|'sales'|'purchases';
const config={
 customers:{title:'Clientes',endpoint:'/customers',columns:[['firstName','Nombre'],['lastName','Apellido'],['email','Correo'],['phone','Teléfono'],['rfc','RFC'],['status','Estado']],fields:['firstName','lastName','email','phone','rfc','address','city','state','postalCode','notes']},
 suppliers:{title:'Proveedores',endpoint:'/suppliers',columns:[['name','Proveedor'],['contactName','Contacto'],['email','Correo'],['phone','Teléfono'],['rfc','RFC'],['status','Estado']],fields:['name','contactName','email','phone','rfc','address','notes']},
 sales:{title:'Ventas',endpoint:'/sales',columns:[['folio','Folio'],['customerName','Cliente'],['saleDate','Fecha'],['total','Total'],['paymentMethod','Pago'],['status','Estado']],fields:[]},
 purchases:{title:'Compras',endpoint:'/purchases',columns:[['folio','Folio'],['supplierName','Proveedor'],['purchaseDate','Fecha'],['total','Total'],['status','Estado']],fields:[]}
} as const;
const labels:Record<string,string>={firstName:'Nombre',lastName:'Apellido',name:'Proveedor',contactName:'Contacto',email:'Correo',phone:'Teléfono',rfc:'RFC',address:'Dirección',city:'Ciudad',state:'Estado/Provincia',postalCode:'Código postal',notes:'Notas'};

export function RecordsWorkspace({kind,session}:{kind:Kind;session:Session}){
 const cfg=config[kind]; const [rows,setRows]=useState<Row[]>([]); const [selected,setSelected]=useState<string[]>([]); const [search,setSearch]=useState(''); const [loading,setLoading]=useState(true); const [error,setError]=useState(''); const [editing,setEditing]=useState<Row|null>(null); const [open,setOpen]=useState(false); const [form,setForm]=useState<Record<string,string>>({});
 const load=async()=>{setLoading(true);setError('');try{const result=await apiRequest<any>('GET',cfg.endpoint+(search?'?search='+encodeURIComponent(search):''),undefined,session);setRows(Array.isArray(result)?result:Array.isArray(result?.data)?result.data:[]);}catch(e){setError(apiErrorMessage(e));}finally{setLoading(false);}};
 useEffect(()=>{void load();},[kind]);
 const filtered=useMemo(()=>rows.filter(row=>!search||JSON.stringify(row).toLowerCase().includes(search.toLowerCase())),[rows,search]);
 const begin=(row?:Row)=>{setEditing(row??null);const values:Record<string,string>={};for(const f of cfg.fields)values[f]=row?.[f]==null?'':String(row[f]);setForm(values);setOpen(true);};
 const save=async(e:React.FormEvent)=>{e.preventDefault();try{const id=String(editing?._id??'');await apiRequest(editing?'PUT':'POST',editing?cfg.endpoint+'/'+id:cfg.endpoint,form,session);setOpen(false);await load();}catch(err){setError(apiErrorMessage(err));}};
 const remove=async(row:Row)=>{if(!confirm('¿Eliminar este registro?'))return;try{await apiRequest('DELETE',cfg.endpoint+'/'+String(row._id),undefined,session);await load();}catch(e){setError(apiErrorMessage(e));}};
 const purchasePdf=async(row:Row)=>{try{const id=String(row._id);await apiDownload('/purchases/'+id+'/report.pdf',session,'compra-'+String(row.folio??id)+'.pdf');}catch(e){setError(apiErrorMessage(e));}};
 const packagePdf=async()=>{if(!selected.length){setError('Selecciona al menos una compra.');return;}try{await apiDownloadPost('/purchases/reports/package.pdf',{ids:selected},session,'paquete-compras.pdf');}catch(e){setError(apiErrorMessage(e));}};
 const togglePurchase=(id:string)=>setSelected(v=>v.includes(id)?v.filter(x=>x!==id):[...v,id]);
 return <div className="workspace-main">
  <div className="page-heading"><div><span className="eyebrow">OPERACIÓN / REGISTROS</span><h1 className="page-title">{cfg.title}</h1><p className="page-description">Consulta y administra los registros de tu organización.</p></div>{kind!=='sales'&&kind!=='purchases'&&<button className="primary-button compact-button" onClick={()=>begin()}>Nuevo registro</button>}</div>
  {error&&<div className="products-error">{error}</div>}
  {kind==='purchases'&&<div className="list-toolbar"><strong>Reportes de compras</strong><button className="primary-button compact-button" disabled={!selected.length} onClick={()=>void packagePdf()}>Reporte paquete ({selected.length})</button><span className="record-count">Selecciona las compras que quieras agrupar</span></div>}
  <div className="list-toolbar"><input className="search-field" value={search} onChange={e=>setSearch(e.target.value)} placeholder={'Buscar en '+cfg.title.toLowerCase()}/><button className="secondary-button" onClick={()=>void load()}>Buscar / actualizar</button><span className="record-count">{filtered.length} registros</span></div>
  <div className="content-panel table-panel">{loading?<div className="loading-state">Cargando…</div>:filtered.length===0?<div className="empty-state"><strong>Sin registros</strong><span className="empty-copy">Crea el primer registro para comenzar.</span></div>:<div className="table-scroll"><table className="data-table"><thead><tr>{kind==='purchases'&&<th>Paquete</th>}{cfg.columns.map(c=><th key={c[0]}>{c[1]}</th>)}{kind!=='sales'&&<th>Acciones</th>}</tr></thead><tbody>{filtered.map((row,i)=>{const id=String(row._id??i);return <tr key={id}>{kind==='purchases'&&<td><input type="checkbox" checked={selected.includes(id)} onChange={()=>togglePurchase(id)} aria-label={'Seleccionar '+String(row.folio??'compra')}/></td>}{cfg.columns.map(c=><td key={c[0]}>{format(row[c[0]])}</td>)}{kind==='purchases'?<td className="row-actions"><button className="table-action" onClick={()=>void purchasePdf(row)}>Reporte PDF</button></td>:kind!=='sales'&&<td className="row-actions"><button className="table-action" onClick={()=>begin(row)}>Editar</button><button className="table-action danger-action" onClick={()=>void remove(row)}>Eliminar</button></td>}</tr>})}</tbody></table></div>}</div>
  {open&&<div className="dialog-backdrop" onMouseDown={e=>{if(e.target===e.currentTarget)setOpen(false)}}><section className="record-dialog"><header className="dialog-heading"><h2>{editing?'Editar':'Nuevo'} {cfg.title.slice(0,-1).toLowerCase()}</h2><button className="dialog-close" onClick={()=>setOpen(false)}>×</button></header><form className="record-form" onSubmit={save}>{cfg.fields.map(f=><label className="field-label" key={f}>{labels[f]??f}<input className="text-field" value={form[f]??''} required={f==='firstName'||f==='name'} onChange={e=>setForm(v=>({...v,[f]:e.target.value}))}/></label>)}<div className="dialog-actions"><button type="button" className="secondary-button" onClick={()=>setOpen(false)}>Cancelar</button><button className="primary-button compact-button" type="submit">Guardar</button></div></form></section></div>}
 </div>;
}
function format(value:unknown){if(value==null||value==='')return '—';if(typeof value==='number')return new Intl.NumberFormat('es-MX',{maximumFractionDigits:2}).format(value);if(typeof value==='string'&&/^\d{4}-\d{2}-\d{2}T/.test(value))return new Date(value).toLocaleString('es-MX');return String(value);}
